### PR TITLE
API: ending : in area detector prefix

### LINKED ISSUE #161: Adjust cam loader
Slight API change: prefixes must include colon, see https://github.com/pcdshub/pcdsdevices/pull/313

### PR DESCRIPTION
**Pull request by ZLLentz**
closes #161 

I didn't check this at all, hopefully nothing broke. If it did it's probably just testing infrastructure. This probably won't build until pcdsdevices is tagged.

### CODE REVIEW

**Comment by klauer** [comment]
This still valid?

**Comment by ZLLentz** [comment]
Almost certainly still valid, just nobody has complained about their loaded area detectors not working. Which they probably don't...

**Comment by ZLLentz** [comment]
Master has PVs like `HXX:UM6:CVV:01Acquire_RBV` for a camera in xcs

I say we merge this and tag again

**Comment by ZLLentz** [comment]
I think this one is squarely my bad. Check out that PR date.

**Comment by ZLLentz** [comment]
Not a single soul has tried to use the area detector objects via hutch-python since at least 2018

**Pull request merged**
