### PR TITLE
ENH: pcds-ci-helpers usage

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Switch to using pcds-ci-helpers in the travis file

## Motivation and Context

Long overdue + sidestep a travis setup bug in the original config

## How Has This Been Tested?

CI works

### CODE REVIEW

**Comment by ZLLentz** [comment]
I was hoping to solve this before the tag, but I'm confused about the ipynotebook/sphynx/pandoc errors.

**Comment by klauer** [comment]
Strange that including `pandoc` in the requirements didn't install it - unless `pypandoc` is also required?

**Comment by ZLLentz** [comment]
Worth a try

**Comment by ZLLentz** [comment]
Uh ok then I guess that's great

**Comment by ZLLentz** [comment]
Self-merging this CI fix that has been plaguing the repo for a while

**Pull request merged**
