### PR TITLE
DOC: run release notes script for v1.18.1

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Get release notes ready for the tag

## Motivation and Context

I want to tag every package that I help maintain since we haven't done this at all in 2023.

## How Has This Been Tested?

n/a

## Where Has This Been Documented?

is docs

### CODE REVIEW

**Review by tangkong — APPROVED** [review]
Seems like we've been ignoring the tests that fail here, or at least procrastinating on fixing them.  This should be good to go probably.

**Comment by ZLLentz** [comment]
You're right, looks like I've put it on the backburner. See #357

**Comment by ZLLentz** [comment]
The weird pip failure was only in a workflow running on my fork, rather than the workflow running here :confused:

**Review by klauer — APPROVED** [review]

**Comment by ZLLentz** [comment]
Yes, IPython is currently on the "do not update this basically ever" list due to past pain with unexpected breaks or behavior changes between minor releases.

**Pull request merged**
