### PR TITLE
ENH: use pcdsutils to configure logstash logger

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Set up this logger at the application level for any user code that sends messages to logstash

## Motivation and Context

Logging configuration is the responsibility of the application to maximize library portability

### CODE REVIEW

**Comment by klauer** [comment]
Looks like a `configure_pcds_loging` typo failing the build

**Comment by ZLLentz** [comment]
I'm the king of typos today! The best at loging and the manifastest!

**Comment by ZLLentz** [comment]
@klauer did I understand correctly that it is best to just call with default args and let environment variable overrides happen if needed?

**Comment by klauer** [comment]
Yeah, I think that's the best way to do it as-is - if you have a better idea, though, I'm happy to push those changes into pcdsutils sooner rather than later.

**Comment by ZLLentz** [comment]
Thinking about it a bit more, I think that environment variables are unambiguously the correct way to configure things like servers, ports, etc., because we do not want to go around adding lots of the same arguments to every application.

typhos --logstash-server --logstash-port --logstash-stash-stash
hutch-python --logstash-stash-stash
etc.

**Pull request merged**
