### PR TITLE
ENH: add a few simulated motors by default

### LINKED ISSUE #208: Include Fake Testing Hardware e.g. Motors
## Expected Behavior

- Default load a tst or sim namespace of useful test hardware

## Current Behavior

- no such feature

## Possible Solution

- Use pcdsdevices.sim.FastMotor and pcdsdevices.sim.SlowMotor

## Context

- Easy disambiguation of test issues

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Add three fast motors that reach the destination immediately
Add three slow motors that reach the destination slowly

## Motivation and Context

closes #208

## How Has This Been Tested?

Locally

### CODE REVIEW

**Comment by ZLLentz** [comment]
I'm not going to add the ophyd simulated hardware because I think users will be confused as to why our extra methods aren't available. I could not find a good simulated detector proxy for the ami stuff.

**Review by klauer — APPROVED** [review]
I think that's reasonable.

Wonder what `ophyd.sim` with `pcdsdevices.interface` would look like.

**Review by ZryletTC — COMMENTED** [review]
Those'll be nice to have 👍 
They might not be AmiDets but the ophyd.sim dets can still be helpful maybe?

**Review by ZryletTC — APPROVED** [review]

**Comment by klauer** [comment]
Ready for a merge?

**Comment by ZLLentz** [comment]
Sorry, I went through a "do TMO work and ignore github" swing

**Comment by ZLLentz** [comment]
`ophyd.sim` dets could still be useful, e.g. if we lock them to the fast/slow motors with a syn gauss like in ophyd. Fast/slow is provided here because they have the fltmvinterface functions.

**Pull request merged**
