### PR TITLE
ENH: load_cache doc annotations

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Annotate load_conf.py with docs for each item added
- Make sure these doc strings get included in the namespace table summaries
- Reorganize so that all items are added to the cache in the same way (previously, some debug utilities and misc were strapped on after the normal load process)

## Motivation and Context

- Need some top-level documentation as a companion to #267 which works great for everything that isn't too generic
- E.g. namespaces will now have  quick blurb about what exactly they are namespaces for

## How Has This Been Tested?

- Existing tests still pass

## Where Has This Been Documented?

- Expanded release notes

### CODE REVIEW

**Review by klauer — APPROVED** [review]
Gave this a spin locally. Works pretty great, and code is clean, too.

Only one minor thing is:
`bp?` gives
image

whereas `bp` gives:
image

I think it's more than good enough for now though.

**Comment by ZLLentz** [comment]
ah bizarre, I wonder what went wrong there

**Comment by ZLLentz** [comment]
I see, the pretty table has a hard-coded table header while the `__doc__` is just my extra added text plus the table

**Comment by klauer** [comment]
Slightly wonky implementation from me is what happened 😁 - `__repr__` (generated dynamically) is different from `__doc__` (generated at init)

**Comment by ZLLentz** [comment]
Ok I'm just going to address the test failure then (checking terminal width fails if there is no terminal)

**Pull request merged**
