### PR TITLE
DOC/BLD: v1.18.0 release notes, update dependencies

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

- Run the docs script that @tangkong added in #350 
- Add my info from prior to those scripts
- Reclassify lightpath update as a feature
- Require python 3.9, lightpath 1.0.1

## Motivation and Context

- Get a tag out for conda env
- lightpath update is a pretty big deal, even if the line count was low here, so I thought it deserved more than a bugfix number
- 3.9 is required for pcdsdevices anyway, lightpath 1.0.1 is the reality of #350

## How Has This Been Tested?

- Hopefully the tests still pass

## Where Has This Been Documented?

- This is docs

### CODE REVIEW

**Comment by tangkong** [comment]
We should change the pip-requirements too right?  pcdsdevices at least should get bumped, and maybe lightpath is available on pypi now?

**Comment by ZLLentz** [comment]
Good call, I completely forgot

**Comment by ZLLentz** [comment]
Is this correct now?

**Comment by ZLLentz** [comment]
@tangkong we good to go for the tag?

**Review by tangkong — APPROVED** [review]
Looks good to me 👍

**Pull request merged**
