### PR TITLE
MNT: happi API changes

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

We're generalizing and cleaning up `happi`, so some API is changing. This adjusts `hutch-python` for it.

## How Has This Been Tested?

Tested locally with dev builds until a release of happi + lightpath

attn @klauer @hhslepicka 

There might be some need for a `DummyBackend` for stuff like the conftest hack that failed here

### CODE REVIEW

**Comment by klauer** [comment]
What about instead of a dummy backend, we have a temporary configuration fixture that uses the json backend?

**Comment by ZLLentz** [comment]
That seems good to me

**Comment by ZLLentz** [comment]
I will let this sit here until we finish the happi refactors

**Comment by klauer** [comment]
Looks like pcdsdevices now, maybe?

**Comment by ZLLentz** [comment]
Yep, it's definitely (at least partly) in need of a `pcdsdevices` tag

**Comment by ZLLentz** [comment]
I'll dig into the rest. I'd like all the packages to work together by the end of the week...

**Comment by ZLLentz** [comment]
Ah. This depends on lightpath. I'll make a tag there before assuming there's a rabbit hole to enter.

**Comment by klauer** [comment]
Makes sense!

**Pull request merged**
