### PR TITLE
ENH: query the user if their beamline config fails to load

### LINKED ISSUE #192: More Dramatic Failure for Beamline and Experiment Files
## Expected Behavior

The user should be very aware if their user-defined files (beamline, experiment, etc.) failed to load and why they failed to load, and that any devices defined within them will be unavailable.

## Current Behavior

The  beamline file can claim that all of its contents succeeded, but then fail at the end with just a small red line in the load sequence. Then, all the items that claimed success are actually missing!

## Possible Solution

When files to load from are provided but raise exceptions in their loading, we should either:
1. Show an error message with the traceback, but continue loading
2. Show an error message with the traceback, and quit execution

I don't believe it is possible to do a partial load of these user files.

### PR DESCRIPTION
**Pull request by klauer**
## Description
Any exception raised while loading the user file will cause every other importable device/function/etc to not appear in the overall hutch-python user namespace.

Instead of continuing with a small and easy to skip message, this PR adds the functionality of querying the user to continue.

## Motivation and Context
Closes #192 

## How Has This Been Tested?
Interactively.

```
INFO     Loading klauer.beamline...
klauer beamline
ERROR    Failed to load klauer.beamline
Traceback (most recent call last):
  File "/Users/klauer/Repos/hutch-python/hutch_python/user_load.py", line 37, in get_user_objs
    module_objs = extract_objs(module)
  File "/Users/klauer/Repos/hutch-python/hutch_python/utils.py", line 169, in extract_objs
    scope = import_module(scope)
  File "/Users/klauer/mc/envs/lucid/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/klauer/Repos/hutch-python/klauer/beamline.py", line 5, in <module>
    raise ValueError('test')
ValueError: test
ERROR    Devices and functions from module 'klauer.beamline' will NOT be available because it failed to load with:
         ValueError: test.
Continue loading hutch-python? [Yn]
```

## Screenshots (if appropriate):
Colored logging helps accentuate the error:

image

### CODE REVIEW

**Comment by ZLLentz** [comment]
This looks very clean. I think we should have the same message on the experiment files too, since this is another user code entry point.

**Review by ZLLentz — APPROVED** [review]
LGTM, this will help a lot on the beamline when setting up experiments. Good catch on skipping the ask-on-exit for missing experiment file.

**Comment by ZLLentz** [comment]
Can I merge this?

**Comment by klauer** [comment]
Ready on my end 👍

**Pull request merged**
