### PR TITLE
DOC: document how to use hutch-python resources in a jupyter notebook

### PR DESCRIPTION
**Pull request by ZLLentz**
## Description

Adds a jupyter notebook with an explanation on how to use hutch-python in jupyter

## Motivation and Context

https://jira.slac.stanford.edu/browse/ECS-4353

## How Has This Been Tested?

All the imports work, but needs more testing

## Where Has This Been Documented?

This is docs

## Pre-merge checklist
- [ ] Code works interactively (a real hutch config file can be loaded)
- [ ] Code contains descriptive docstrings, including context and API
- [ ] New/changed functions and methods are covered in the test suite where possible
- [ ] Test suite passes locally
- [ ] Test suite passes on GitHub Actions
- [ ] Ran ``docs/pre-release-notes.sh`` and created a pre-release documentation page
- [ ] Pre-release docs include context, functional descriptions, and contributors as appropriate

### CODE REVIEW

**Comment by ZLLentz** [comment]
Would it be worthwhile to finish the checklist and merge this, or should I close it? @tangkong

**Comment by tangkong** [comment]
My objections to bluesky-in-jupyter aside, I think it's good to preserve your work on this.  I don't think the checklist matters too much here.

**Comment by ZLLentz** [comment]
I'll do pre-release-notes at least

**Review by tangkong — APPROVED** [review]
LGTM

**Pull request merged**
